spring.application.name=pastel

# DB用設定
spring.datasource.url=jdbc:sqlite:data/pastel.db
spring.datasource.hikari.maximum-pool-size=1

# AI設定
#spring.ai.anthropic.chat.model=claude-haiku-4-5
spring.ai.anthropic.chat.model=claude-sonnet-5-5
spring.ai.anthropic.chat.max-tokens=4096
spring.config.import=optional:file:.env[.properties]
spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
spring.ai.anthropic.chat.web-search-tool.max-uses=3
spring.ai.anthropic.chat.web-search-tool.user-location.country=JP
spring.ai.anthropic.chat.web-search-tool.user-location.timezone=Asia/Tokyo

# PASTEL.mdのバージョン
pastel.md-version=0.0.5